analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 1
title: Kickstart Marketing and Design  Inc.
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 1
  brandStrength: 0.5
  rhythmicContrast: 0
  brandColors:
    - '#3ea7ba'
    - '#48555d'
    - '#ffffff'
    - '#a2d5dd'
    - '#758086'
  lightness: 1
purpose: []
favicon: null
name: Kickstart Inc
typography_spectrum: 0.57582
