name: kickstartinc
favicon: null
layout_spectrum: 0.24903118470683694
typography_spectrum: 0.4867916922084987
title: Kickstart Marketing and Design  Inc.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a2a1a7'
    - '#5f5b5c'
    - '#ced2db'
    - '#0b6995'
    - '#fefefe'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
