name: Kickstart Inc
favicon: null
layout_spectrum: 0.51412
typography_spectrum: 0.40132
title: Kickstart Marketing and Design  Inc.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0dadc5'
    - '#ffffff'
    - '#003f62'
    - '#86d6e2'
    - '#fbe91a'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
